<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>

    <!-- Mengaktifkan Native AOT (Otomatis Single Binary) -->
    <PublishAot>true</PublishAot>

    <!-- Optimasi Ukuran & Trim -->
    <OptimizationPreference>Speed</OptimizationPreference>
    <InvariantGlobalization>true</InvariantGlobalization>
    <StackTraceSupport>false</StackTraceSupport>
    <EventSourceSupport>false</EventSourceSupport>

    <!-- Strip & Debug Symbols -->
    <StripSymbols>true</StripSymbols>
    <DebugType>none</DebugType>
    <DebugSymbols>false</DebugSymbols>
  </PropertyGroup>

</Project>
